### ISSUE TITLE
Extract the hashing module

### ISSUE THREAD

**Issue by RiccardoM** [Commercionetwork/Borsellino#1]
Currently the `hashing` module is a Kotlin pure implementation of some hashing functions such as SHA1-256, SHA3 and RIPEMD. 

In order to allow other projects to use this code without having to depend on Borsellino, we should move this code inside an external library.

**Comment by ligi** [comment]
sha3 is already a separate project: https://github.com/walleth/sha3

as far as I see the sha3 code inside here is this code - so extracting it would end up being a dup of walleth/sha3. Let's try to not fragment further but to converge again

**Comment by RiccardoM** [comment]
@ligi Unfortunately, I've already started separating the whole implementation of SHA3, RIPEMD160 and SHA2 inside the [Khashing](https://github.com/Commercionetwork/Khashing) project. 

This has been done for two main reasons. 

1. We need to have a code base that we can security audit, and you probably know that we cannot audit a code that is not ours. 

2. After seeing [your response ](https://github.com/walleth/kethereum/pull/63#issuecomment-474170872) about converting the SHA3 library to a multiplatform library, I wrongly thought you were not ok with that. 

These factors led me into the decision of separating the implementation of the hashing functions that other users might try useful. 

Also, as you've correctly pointed out, the code inside the Khashing `keccak` module is the same of the one present inside the WallETH SHA3 library. This means that, if you want, you can swipe the two of them very easily. I've just tweaked the documentation to make it more clear and added inside the same library other hashing functions that could be extracted from WallETH/Borsellino.

**Comment by ligi** [comment]
> We need to have a code base that we can security audit, and you probably know that we cannot audit a code that is not ours.

no - what is the reason for this?

> After seeing your response about converting the SHA3 library to a multiplatform library, I wrongly thought you were not ok with that.

yea - this is not what I ment - I was stating that copying the code is a bad idea as it makes things wet and not dry

**Comment by RiccardoM** [comment]
> no - what is the reason for this?

As far as I know, but I might be wrong, when you audit a code that code cannot change until a new audit is done on it.  

For example, let's assume we keep implementing all the things inside WallETH/SHA3 or any other of your libraries. Now, let's say that we audit the version 1.0 of your code. You should then wait to publish a new version of the library until a new security audit is done on all the changes made since version 1.0.  

As you can imagine, this makes it very hard to audit libraries that are maintained from individuals, as they might create a lot of versions to fix small bugs or implement things that they might find useful.  

That's why our company thought it might be better to have a codebase that we can keep stable for long periods of time and audit once in a while to produce a stable release that the users can use safely. 

> yea - this is not what I ment - I was stating that copying the code is a bad idea as it makes things wet and not dry

I 100% agree with you on this. That's the main reason we've created the Khashing library that allows Java developers as well as multiplatform ones to use that library.

**Comment by ligi** [comment]
> As far as I know, but I might be wrong, when you audit a code that code cannot change until a new audit is done on it.

no - an audit usually contains the commit hash on which it was done - you can change the code - but it is only audited until this commit hash. So you can audit code that is not "yours" - I really see no difference there and no reason to make the code "yours"

>  100% agree with you on this. That's the main reason we've created the Khashing library that allows Java developers as well as multiplatform ones to use that library.

that could have been done in the walleth/sha3 library - I would have been totally open to this. My *question*

> is there really no other way?

was just referring to your statement:

> Note. In order to make this library 100% multiplatform, I had to copy/paste the Walleth/HEX and Wallet/SHA3 classes inside the project. 

as I really dislike this copy/paste - this only makes things WET and I like to keep things DRY

Please reconsider this move of just making the code "yours" - not only is it creating unnecessary fragmentation - but as it is currently it is also a license violation https://github.com/Commercionetwork/Khashing
